### ISSUE TITLE
Feature Request: One-to-one relationship trait

### ISSUE THREAD

**Issue by SteJaySulli** [DivineOmega/laravel-addresses#1]
At the moment we have a `hasAddresses` trait, which is great for implementations that require a number of addresses to be stored against a model, but we could also do with a matching `hasAddress` trait for one-to-one relationships.

**Comment by Jord-JD** [comment]
Great idea. Adding in a `HasAddress` trait.

https://github.com/DivineOmega/laravel-addresses/commit/44adef1b1800e2a81412968ffd2d487c0e65cf42

**Comment by Jord-JD** [comment]
Released as part of [v1.1.0](https://github.com/DivineOmega/laravel-addresses/releases/tag/v1.1.0).
